version: '3.3'

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: 7ewm5xfw/foodgram_backend:v22.05.2022
    build:
      context: ""
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ../backend/:/app/

  frontend:
    image: 7ewm5xfw/foodgram_frontend:v22.05.2022
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - ../backend/static:/var/html/static/
      - ../backend/media:/var/html/media/
    depends_on:
      - backend
      - frontend
volumes:
  postgres_data:
  static_value:
  media_value:
